= Dolly - an opinionated build system for Bluespec SystemVerilog projects.

Dolly is an attempt to simplify building BSV projects by formalizing a simple project structure that allows the build system to quickly find modules and test benches.  It's written in Rust and is designed to very roughly approximate how Rust's own Cargo build system works.

  Currently Dolly does *not* currently support integration with C submodules.   This is a planned feature extension.

== Project layout and dolly.toml

The build system's main configuration file is name dolly.toml and lives at the project's root.  From there, the project is expected to be structured as follows:

[source]
----
project/
    src/
        submodule1/
            submodule3/
        submodule2/
        packagename.bsv
    tests/
    dolly.toml
----

== How dolly finds modules and submodules.

When run, the first thing dolly loads is dolly.toml in the project root.  Inside that file, the name of the package is defined.  This package name is used to find the root of the module tree inside the 'src' directory.  Here's an example dolly.toml:

[source]
----
[package]
name = "SampleProject"
version = "0.1.0"
----

Dolly looks in this file for the 'name' property inside the 'package' section.  In the example above, the package name is "SampleProject" and dolly will look for the root of the project at 'src/SampleProject.bsv'.  Now that the root of the project has been located, dolly attempt to locate submodules be parsing SampleProject looking for submodule directives structured as BSV comments.  As an example, suppose 'src/SampleProject.bsv' has the following structure:

[source]
----
    //!submodule submodule1
    //!submodule submodule2

    ... other BSV source here ...
----

Dolly will use directives that start with '//!submodule <submodulename>' to inform the BSV compiler about additional submodules.  In the above example, the BSV compiler will be told about the 'submodule1' and 'submodule2' directories.  This process is recursive - dolly will look for a file named 'submodule1.bsv' inside the submodule1 directory and will again parse that file looking for submodule directives.  

    These submodule directives is how dolly learns about the module structure of the project.

== How Dolly finds unit testbenches

When run, in addition to finding modules and submodules, dolly also looks for unit testbench files of the form '<testbench>_tb.bsv'.  If found dolly will add these to the list of unit testbenches that are available to dolly for testing.  As an example, suppose you're creating a module and you want to create a unit testbench - it may be structured like this:

[source]
----
myproject/
    src/
        myproject.bsv
        mytestable_module.bsv
        mytestable_module_tb.bsv
----

Dolly will notice mytestable_module_tb.bsv and look for a module named "mkTopModule" and will execute that as part of dolly's testing mechanism.  There can be any number of <file>_tb.bsv files located in module/submodule directories.

== How Dolly finds integration testbenches

In addition to the unit testbenches above, Dolly also supports higher-level testbenches meant to perform integration tests of the main project top module.  These integration tests are located in the tests directory inside the project's root directory.  Each file inside will be treated as a separate BSV executable and will be run as part of Dolly's testing framework.

== How Dolly determines if a testbench succeeds or fails.

To determine if a testbench succeeds or fails, Dolly will parse the test's output looking for the string ">>>PASS" and if found, dolly will note the specific test as passed.  If that string is not found in the output, the test will be marked as failed.

== Running Dolly

Dolly has several modes of operation, each disussed below.

=== Running testbenches

To execute all testbenches, run Dolly using the 'test' command.

[shell]
====
$ dolly test

====

=== Generating Verilog

To generate Verilog from the project's top module, run Dolly using the 'build' command.

[shell]
====
$ dolly build
====

The verilog files will be located in the target/<topmodule>/<topmodule>.v (where <topmodule> is the topmodule name specified in the src/<packagename>.bsv)

For example, if your project is named "MyProject", the topmodules specified in src/MyProject.bsv will be used to generate Verilog.

[source]
====
    //!submodule Submodule1
    //!submodule Submodule2

    //!topmodule mkFirstModule
    module mkFirstModule(Empty);
        // Module source here
    endmodule
====

Will generate target/mkFirstModule/mkFirstModule.v.

== Dolly in-source directives

Dolly has several directives that can be specified to modify certain dolly behavior.

=== //!topmodule TestBenchName

The !topmodule directive will inform dolly of the name of the topmodule for the given testbench instead of the default 'mkTopModule'.

For example, to specify that the top module for a particular test bench is name mkTestBench instead of the default (mkTopModule), use the following:

[source]
====
    //!topmodule mkTestBench

    module mkTestBench(Empty);
        rule run_it;
            // Required for test to pass.
            $display(">>>PASS");
            $finish();
        endrule
    endmodule
====
